# Generated by Django 5.0.2 on 2024-03-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="method",
            field=models.CharField(choices=[("ALLOW", "allow"), ("DENY", "deny")]),
        ),
    ]
