# Generated by Django 5.0.2 on 2024-03-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0001_initial"),
        ("resource", "0002_alter_resourcegroup_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iamuser",
            name="permissions",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="resource.resourcepermission"
            ),
        ),
        migrations.AlterField(
            model_name="iamuser",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="iam.role"
            ),
        ),
    ]
