# Generated by Django 5.0.2 on 2024-09-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0002_alter_iamuser_permissions_alter_iamuser_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iamuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="iamuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
