# Generated by Django 5.0.2 on 2024-03-27 19:04

import datetime
import django.db.models.deletion
import django_celery_beat.models
import django_celery_beat.validators
import timezone_field.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("flow", "0004_alter_slot_speciality"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodicScheduler",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scheduler_type",
                    models.CharField(
                        choices=[("interval", "Interval"), ("crontab", "Crontab")],
                        default="interval",
                        max_length=10,
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        default=datetime.timedelta(seconds=60), verbose_name="Duration"
                    ),
                ),
                (
                    "minute",
                    models.CharField(
                        default="*",
                        help_text='Cron Minutes to Run. Use "*" for "all". (Example: "0,30")',
                        max_length=240,
                        validators=[django_celery_beat.validators.minute_validator],
                        verbose_name="Minute(s)",
                    ),
                ),
                (
                    "hour",
                    models.CharField(
                        default="*",
                        help_text='Cron Hours to Run. Use "*" for "all". (Example: "8,20")',
                        max_length=96,
                        validators=[django_celery_beat.validators.hour_validator],
                        verbose_name="Hour(s)",
                    ),
                ),
                (
                    "day_of_month",
                    models.CharField(
                        default="*",
                        help_text='Cron Days Of The Month to Run. Use "*" for "all". (Example: "1,15")',
                        max_length=124,
                        validators=[
                            django_celery_beat.validators.day_of_month_validator
                        ],
                        verbose_name="Day(s) Of The Month",
                    ),
                ),
                (
                    "month_of_year",
                    models.CharField(
                        default="*",
                        help_text='Cron Months (1-12) Of The Year to Run. Use "*" for "all". (Example: "1,12")',
                        max_length=64,
                        validators=[
                            django_celery_beat.validators.month_of_year_validator
                        ],
                        verbose_name="Month(s) Of The Year",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        default="*",
                        help_text='Cron Days Of The Week to Run. Use "*" for "all", Sunday is 0 or 7, Monday is 1. (Example: "0,5")',
                        max_length=64,
                        validators=[
                            django_celery_beat.validators.day_of_week_validator
                        ],
                        verbose_name="Day(s) Of The Week",
                    ),
                ),
                (
                    "timezone",
                    timezone_field.fields.TimeZoneField(
                        default=django_celery_beat.models.crontab_schedule_celery_timezone,
                        help_text="Timezone to Run the Cron Schedule on. Default is UTC.",
                        use_pytz=False,
                        verbose_name="Cron Timezone",
                    ),
                ),
                (
                    "node",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="flow.basenode"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WebHookScheduler",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "node",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="flow.basenode"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
