version: "3.8"

services:
  backend:
    container_name: astrikos_backend
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    image: astrikos_backend
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/astrikos
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: astrikos_db
    hostname: ${POSTGRES_HOST}
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}", "-h", "${POSTGRES_HOST}"]
      interval: 5s
      retries: 5
      timeout: 5s


volumes:
  db:
