import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]
DEBUG = int(os.environ["DEBUG"])

# Postgres
POSTGRES_HOST = os.environ["POSTGRES_HOST"]
POSTGRES_DB = os.environ["POSTGRES_DB"]
POSTGRES_USER = os.environ["POSTGRES_USER"]
POSTGRES_PASSWORD = os.environ["POSTGRES_PASSWORD"]
POSTGRES_PORT = os.environ["POSTGRES_PORT"]

# Timescaledb
TIMESCALE_HOST = os.environ["TIMESCALE_HOST"]
TIMESCALE_DB = os.environ["TIMESCALE_DB"]
TIMESCALE_USER = os.environ["TIMESCALE_USER"]
TIMESCALE_PASSWORD = os.environ["TIMESCALE_PASSWORD"]
TIMESCALE_PORT = os.environ["TIMESCALE_PORT"]

# RabbitMQ
RABBITMQ_HOST = os.environ["RABBITMQ_HOST"]
RABBITMQ_DEFAULT_USER = os.environ["RABBITMQ_DEFAULT_USER"]
RABBITMQ_DEFAULT_PASS = os.environ["RABBITMQ_DEFAULT_PASS"]
BROKER_PORT = os.getenv("BROKER_PORT", 5672)

RABBITMQ_CELERY_BROKER_URL = f"amqp://{RABBITMQ_DEFAULT_USER}:{RABBITMQ_DEFAULT_PASS}@{RABBITMQ_HOST}:{BROKER_PORT}"
RABBITMQ_CELERY_RESULT_BACKEND = "django-db"

# InfluxDB
INFLUXDB_HOST = os.environ["INFLUXDB_HOST"]
INFLUXDB_PORT = os.environ["INFLUXDB_PORT"]
INFLUXDB_TOKEN = os.environ["INFLUXDB_TOKEN"]
INFLUXDB_ORG = os.environ["INFLUXDB_ORG"]
INFLUXDB_BUCKET = os.environ["INFLUXDB_BUCKET"]

INFLUXDB_URI = f"http://{INFLUXDB_HOST}:{INFLUXDB_PORT}"

# Worker
WORKER_URL = os.environ["WORKER_URL"]
