# Generated by Django 5.0.2 on 2024-03-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parameter",
            old_name="node",
            new_name="node_class",
        ),
    ]
