# Generated by Django 5.0.2 on 2024-07-05 22:12

import apps.flow.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("flow_new", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "position",
                    models.JSONField(default=apps.flow.utils.default_position),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dependency",
            fields=[
                (
                    "basemodelwithtag_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="flow_new.basemodelwithtag",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("requirements", models.FileField(upload_to="flow/dependencies/")),
            ],
            options={
                "verbose_name": "Dependency",
                "verbose_name_plural": "Dependencies",
            },
            bases=("flow_new.basemodelwithtag",),
        ),
        migrations.CreateModel(
            name="FunctionDefinition",
            fields=[
                (
                    "basemodelwithtag_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="flow_new.basemodelwithtag",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("code", models.FileField(upload_to="flow/functions/")),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
                "abstract": False,
            },
            bases=("flow_new.basemodelwithtag",),
        ),
        migrations.CreateModel(
            name="ConditionalNode",
            fields=[
                (
                    "basenode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="flow_new.basenode",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
                "abstract": False,
            },
            bases=("flow_new.basenode",),
        ),
        migrations.CreateModel(
            name="DataNode",
            fields=[
                (
                    "basenode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="flow_new.basenode",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=10000)),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
                "abstract": False,
            },
            bases=("flow_new.basenode",),
        ),
        migrations.CreateModel(
            name="ForEachNode",
            fields=[
                (
                    "basenode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="flow_new.basenode",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
                "abstract": False,
            },
            bases=("flow_new.basenode",),
        ),
        migrations.CreateModel(
            name="InputNode",
            fields=[
                (
                    "basenode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="flow_new.basenode",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
                "abstract": False,
            },
            bases=("flow_new.basenode",),
        ),
        migrations.CreateModel(
            name="OutputNode",
            fields=[
                (
                    "basenode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="flow_new.basenode",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
                "abstract": False,
            },
            bases=("flow_new.basenode",),
        ),
        migrations.CreateModel(
            name="Flow",
            fields=[
                (
                    "basemodelwithtag_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="flow_new.basemodelwithtag",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "lib",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flows",
                        to="flow_new.dependency",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
                "abstract": False,
            },
            bases=("flow_new.basemodelwithtag",),
        ),
        migrations.AddField(
            model_name="basenode",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="flow_new.flow",
            ),
        ),
        migrations.CreateModel(
            name="FunctionField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[("IN", "Input"), ("OUT", "Output")], max_length=10
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("INT", "Integer"),
                            ("STR", "String"),
                            ("BOOL", "Boolean"),
                            ("FLOAT", "Float"),
                            ("LIST", "List"),
                            ("SET", "Set"),
                            ("TUPLE", "Tuple"),
                            ("DICT", "Dictionary"),
                            ("NONE", "None"),
                            ("ANY", "Any"),
                        ],
                        default="ANY",
                        max_length=15,
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="flow_new.functiondefinition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[("IN", "Input"), ("OUT", "Output")], max_length=10
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("INT", "Integer"),
                            ("STR", "String"),
                            ("BOOL", "Boolean"),
                            ("FLOAT", "Float"),
                            ("LIST", "List"),
                            ("SET", "Set"),
                            ("TUPLE", "Tuple"),
                            ("DICT", "Dictionary"),
                            ("NONE", "None"),
                            ("ANY", "Any"),
                        ],
                        default="ANY",
                        max_length=15,
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="flow_new.basenode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections_out",
                        to="flow_new.slot",
                    ),
                ),
                (
                    "to_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections_in",
                        to="flow_new.slot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlowNode",
            fields=[
                (
                    "basenode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="flow_new.basenode",
                    ),
                ),
                (
                    "represent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="represent_nodes",
                        to="flow_new.flow",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
                "abstract": False,
            },
            bases=("flow_new.basenode",),
        ),
        migrations.CreateModel(
            name="FunctionNode",
            fields=[
                (
                    "basenode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="flow_new.basenode",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="flow_new.functiondefinition",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
                "abstract": False,
            },
            bases=("flow_new.basenode",),
        ),
        migrations.AddIndex(
            model_name="basenode",
            index=models.Index(fields=["flow"], name="flow_new_ba_flow_id_a9819b_idx"),
        ),
        migrations.AddIndex(
            model_name="functionfield",
            index=models.Index(
                fields=["definition"], name="flow_new_fu_definit_efcb90_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="functionfield",
            unique_together={("name", "definition", "attachment_type")},
        ),
        migrations.AddIndex(
            model_name="slot",
            index=models.Index(fields=["node"], name="flow_new_sl_node_id_1a5a8a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="slot",
            unique_together={("name", "node", "attachment_type")},
        ),
        migrations.AlterUniqueTogether(
            name="connection",
            unique_together={("from_slot", "to_slot")},
        ),
    ]
