# Generated by Django 5.0.2 on 2024-09-23 03:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filearchive",
            options={},
        ),
        migrations.AlterModelOptions(
            name="flow",
            options={},
        ),
        migrations.AlterModelOptions(
            name="functiondefinition",
            options={},
        ),
        migrations.CreateModel(
            name="Prefix",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flow.prefix",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prefix",
                "verbose_name_plural": "Prefixes",
                "unique_together": {("name", "parent")},
            },
        ),
        migrations.AddField(
            model_name="dependency",
            name="prefix",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_items",
                to="flow.prefix",
            ),
        ),
        migrations.AddField(
            model_name="filearchive",
            name="prefix",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_items",
                to="flow.prefix",
            ),
        ),
        migrations.AddField(
            model_name="flow",
            name="prefix",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_items",
                to="flow.prefix",
            ),
        ),
        migrations.AddField(
            model_name="functiondefinition",
            name="prefix",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_items",
                to="flow.prefix",
            ),
        ),
    ]
