# Generated by Django 5.0.2 on 2024-09-23 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0002_alter_filearchive_options_alter_flow_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="tag",
            name="parent",
        ),
        migrations.DeleteModel(
            name="BaseModelWithTag",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
