# Generated by Django 5.0.2 on 2024-03-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0002_rename_node_parameter_node_class"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="connections",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="connections",
            unique_together={("source", "target")},
        ),
    ]
