# Generated by Django 5.0.2 on 2024-09-23 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0003_alter_tag_unique_together_remove_tag_parent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prefix",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="flow.prefix",
            ),
        ),
    ]
