# Generated by Django 5.0.2 on 2024-03-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0003_slot_speciality"),
    ]

    operations = []
