# Generated by Django 5.0.2 on 2024-03-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0004_connections_source_parameter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parameter",
            name="behaviour",
            field=models.CharField(
                choices=[("IN", "Input"), ("OUT", "Output")],
                default="IN",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
