# Generated by Django 5.0.2 on 2024-07-14 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow_new", "0005_scopeblock_alter_foreachnode_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="conditionalnode",
            name="value_type",
            field=models.CharField(
                choices=[
                    ("INT", "Integer"),
                    ("STR", "String"),
                    ("BOOL", "Boolean"),
                    ("FLOAT", "Float"),
                    ("LIST", "List"),
                    ("SET", "Set"),
                    ("TUPLE", "Tuple"),
                    ("DICT", "Dictionary"),
                    ("NONE", "None"),
                    ("ANY", "Any"),
                ],
                default="ANY",
                max_length=15,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="datanode",
            name="value_type",
            field=models.CharField(
                choices=[
                    ("INT", "Integer"),
                    ("STR", "String"),
                    ("BOOL", "Boolean"),
                    ("FLOAT", "Float"),
                    ("LIST", "List"),
                    ("SET", "Set"),
                    ("TUPLE", "Tuple"),
                    ("DICT", "Dictionary"),
                    ("NONE", "None"),
                    ("ANY", "Any"),
                ],
                default="ANY",
                max_length=15,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ConditionalNodeCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "block",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditional_node_case",
                        to="flow_new.scopeblock",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="flow_new.conditionalnode",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="ConditionalNodeValue",
        ),
    ]
