# Generated by Django 5.0.2 on 2024-03-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0005_parameter_behaviour"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parameter",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="parameter",
            unique_together={("name", "node_class")},
        ),
    ]
