# Generated by Django 5.0.2 on 2024-11-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0005_flowexecution"),
    ]

    operations = [
        migrations.AddField(
            model_name="functiondefinition",
            name="doc_str",
            field=models.TextField(blank=True, null=True),
        ),
    ]
