# Generated by Django 5.0.2 on 2024-12-12 07:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0006_functiondefinition_doc_str"),
    ]

    operations = [
        migrations.CreateModel(
            name="FunctionDataStore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("value", models.CharField(max_length=10000)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("INT", "Integer"),
                            ("STR", "String"),
                            ("BOOL", "Boolean"),
                            ("FLOAT", "Float"),
                            ("LIST", "List"),
                            ("SET", "Set"),
                            ("TUPLE", "Tuple"),
                            ("DICT", "Dictionary"),
                            ("NONE", "None"),
                            ("ANY", "Any"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "slot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="flow.slot"
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
                "abstract": False,
            },
        ),
    ]
