# Generated by Django 5.0.2 on 2024-03-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0006_alter_slot_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="speciality",
            field=models.CharField(
                choices=[
                    ("DB", "Database"),
                    ("API", "API"),
                    ("BACKEND", "Backend"),
                    ("NONE", "None"),
                    ("SIG", "Signal"),
                ],
                default="NONE",
                max_length=10,
            ),
        ),
    ]
