# Generated by Django 5.0.2 on 2024-03-14 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0006_alter_parameter_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connections",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_connections",
                to="flow.node",
            ),
        ),
        migrations.AlterField(
            model_name="connections",
            name="source_parameter",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_connections",
                to="flow.parameter",
            ),
        ),
        migrations.AlterField(
            model_name="connections",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_connections",
                to="flow.node",
            ),
        ),
        migrations.AlterField(
            model_name="connections",
            name="target_parameter",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_connections",
                to="flow.parameter",
            ),
        ),
    ]
