# Generated by Django 5.0.2 on 2024-07-21 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow_new", "0007_conditionalnode_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockNode",
            fields=[
                (
                    "basenode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="flow_new.basenode",
                    ),
                ),
                (
                    "block",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_node",
                        to="flow_new.scopeblock",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
                "abstract": False,
            },
            bases=("flow_new.basenode",),
        ),
    ]
