# Generated by Django 5.0.2 on 2024-03-14 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0007_alter_connections_source_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataNodeClass",
            fields=[
                (
                    "nodeclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="flow.nodeclass",
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("INT", "Integer"),
                            ("STR", "String"),
                            ("BOOL", "Boolean"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
                "abstract": False,
            },
            bases=("flow.nodeclass",),
        ),
        migrations.RemoveField(
            model_name="nodeclass",
            name="code",
        ),
        migrations.CreateModel(
            name="DynamicNodeClass",
            fields=[
                (
                    "nodeclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="flow.nodeclass",
                    ),
                ),
                ("code", models.FileField(upload_to="flow/node_classes/")),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
                "abstract": False,
            },
            bases=("flow.nodeclass",),
        ),
    ]
