# Generated by Django 5.0.2 on 2024-12-23 06:41

import apps.flow.utils
import config.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0008_dagmetadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dependency",
            name="requirements",
            field=models.FileField(
                storage=config.storage.OverwriteStorage(),
                upload_to=apps.flow.utils.dependency_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="functiondefinition",
            name="code",
            field=models.FileField(
                storage=config.storage.OverwriteStorage(),
                upload_to=apps.flow.utils.function_upload_path,
            ),
        ),
    ]
