# Generated by Django 5.0.2 on 2024-03-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0008_alter_slot_speciality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datanode",
            name="type",
            field=models.CharField(
                choices=[
                    ("INT", "Integer"),
                    ("STR", "String"),
                    ("BOOL", "Boolean"),
                    ("FLOAT", "Float"),
                    ("LIST", "List"),
                    ("SET", "Set"),
                    ("TUPLE", "Tuple"),
                    ("DICT", "Dictionary"),
                    ("NONE", "None"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="connection",
            unique_together={("source", "target", "source_slot", "target_slot")},
        ),
    ]
