# Generated by Django 5.0.2 on 2024-03-28 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0004_basenode_position"),
        ("flow", "0009_alter_datanode_type_alter_connection_unique_together"),
    ]

    operations = []
