# Generated by Django 5.0.2 on 2024-03-14 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("flow", "0009_flowfile_polymorphic_ctype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowfile",
            name="polymorphic_ctype",
        ),
        migrations.AddField(
            model_name="nodeclass",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
