# Generated by Django 5.0.2 on 2024-03-29 07:50

import apps.flow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0010_merge_20240328_1715"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basenode",
            name="position",
            field=models.JSONField(default=apps.flow.models.default_position),
        ),
        migrations.AlterField(
            model_name="slot",
            name="attachment_type",
            field=models.CharField(
                choices=[
                    ("IN", "Input"),
                    ("OUT", "Output"),
                    ("D_OUT", "Delayed Output"),
                ],
                max_length=5,
            ),
        ),
    ]
