# Generated by Django 5.0.2 on 2024-03-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0011_alter_basenode_position"),
        ("flow", "0011_alter_basenode_position_alter_slot_attachment_type"),
    ]

    operations = []
