# Generated by Django 5.0.2 on 2024-04-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0013_noderesult"),
    ]

    operations = [
        migrations.AddField(
            model_name="basenodeclass",
            name="inputs",
            field=models.JSONField(default=dict),
        ),
    ]
