# Generated by Django 5.0.2 on 2024-04-02 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0014_basenodeclass_inputs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noderesult",
            name="node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="flow.basenode",
            ),
        ),
    ]
