# Generated by Django 5.0.2 on 2024-04-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0017_rename_output_noderesult_inputs_noderesult_outputs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basenodeclass",
            name="inputs",
        ),
    ]
