# Generated by Django 5.0.2 on 2024-06-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0019_environment_flowfile_environment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environment",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
