# Generated by Django 5.0.2 on 2024-06-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0020_alter_environment_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="uploads/")),
            ],
        ),
    ]
