# Generated by Django 5.0.2 on 2024-06-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0021_alter_slot_speciality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="speciality",
            field=models.CharField(
                choices=[
                    ("DB", "Database"),
                    ("API", "API"),
                    ("TB", "Thingsboard"),
                    ("TBQ", "Thingsboard Queue"),
                    ("BACKEND", "Backend"),
                    ("NODE_ID", "Node ID"),
                    ("NONE", "None"),
                    ("SIG", "Signal"),
                ],
                default="NONE",
                max_length=10,
            ),
        ),
    ]
