# Generated by Django 5.0.2 on 2024-06-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0022_alter_slot_speciality"),
    ]

    operations = [
        migrations.AddField(
            model_name="datanode",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
