# Generated by Django 5.0.2 on 2024-06-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0023_datanode_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="speciality",
            field=models.CharField(
                choices=[
                    ("DB", "Database"),
                    ("API", "API"),
                    ("TB", "Thingsboard"),
                    ("TBQ", "Thingsboard Queue"),
                    ("DB_CONNECTOR", "Database Connector"),
                    ("BACKEND", "Backend"),
                    ("NODE_ID", "Node ID"),
                    ("NONE", "None"),
                    ("SIG", "Signal"),
                ],
                default="NONE",
                max_length=50,
            ),
        ),
    ]
