# Generated by Django 5.0.2 on 2024-06-24 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0021_filearchive"),
        ("flow", "0025_alter_datanode_value"),
    ]

    operations = []
