# Generated by Django 5.0.2 on 2024-07-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0026_merge_0021_filearchive_0025_alter_datanode_value"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FileArchive",
        ),
    ]
