# Generated by Django 5.0.2 on 2024-03-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource", "0002_alter_resourcegroup_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcepermission",
            name="name",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
