# Generated by Django 5.0.2 on 2024-06-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource", "0005_datastore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datastore",
            name="identifier",
            field=models.CharField(db_index=True, max_length=1000, unique=True),
        ),
    ]
