# Generated by Django 5.0.2 on 2024-09-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource", "0006_alter_datastore_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datastore",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="datastore",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="resourcegroup",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="resourcegroup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="resourcepermission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="resourcepermission",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
