# Generated by Django 5.0.2 on 2024-03-28 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0007_alter_slot_speciality"),
        ("trigger", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PeriodicScheduler",
            new_name="PeriodicTrigger",
        ),
        migrations.RenameModel(
            old_name="WebHookScheduler",
            new_name="WebHookTrigger",
        ),
    ]
