# Generated by Django 5.0.2 on 2024-09-23 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0002_alter_filearchive_options_alter_flow_options_and_more"),
        ("trigger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodictrigger",
            name="prefix",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_items",
                to="flow.prefix",
            ),
        ),
        migrations.AddField(
            model_name="webhooktrigger",
            name="prefix",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_items",
                to="flow.prefix",
            ),
        ),
    ]
