# Generated by Django 5.0.2 on 2024-03-29 04:47

import django_celery_beat.models
import django_celery_beat.validators
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trigger", "0002_rename_periodicscheduler_periodictrigger_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="periodictrigger",
            name="day_of_month",
            field=models.CharField(
                blank=True,
                default="*",
                help_text='Cron Days Of The Month to Run. Use "*" for "all". (Example: "1,15")',
                max_length=124,
                null=True,
                validators=[django_celery_beat.validators.day_of_month_validator],
                verbose_name="Day(s) Of The Month",
            ),
        ),
        migrations.AlterField(
            model_name="periodictrigger",
            name="day_of_week",
            field=models.CharField(
                blank=True,
                default="*",
                help_text='Cron Days Of The Week to Run. Use "*" for "all", Sunday is 0 or 7, Monday is 1. (Example: "0,5")',
                max_length=64,
                null=True,
                validators=[django_celery_beat.validators.day_of_week_validator],
                verbose_name="Day(s) Of The Week",
            ),
        ),
        migrations.AlterField(
            model_name="periodictrigger",
            name="hour",
            field=models.CharField(
                blank=True,
                default="*",
                help_text='Cron Hours to Run. Use "*" for "all". (Example: "8,20")',
                max_length=96,
                null=True,
                validators=[django_celery_beat.validators.hour_validator],
                verbose_name="Hour(s)",
            ),
        ),
        migrations.AlterField(
            model_name="periodictrigger",
            name="minute",
            field=models.CharField(
                blank=True,
                default="*",
                help_text='Cron Minutes to Run. Use "*" for "all". (Example: "0,30")',
                max_length=240,
                null=True,
                validators=[django_celery_beat.validators.minute_validator],
                verbose_name="Minute(s)",
            ),
        ),
        migrations.AlterField(
            model_name="periodictrigger",
            name="month_of_year",
            field=models.CharField(
                blank=True,
                default="*",
                help_text='Cron Months (1-12) Of The Year to Run. Use "*" for "all". (Example: "1,12")',
                max_length=64,
                null=True,
                validators=[django_celery_beat.validators.month_of_year_validator],
                verbose_name="Month(s) Of The Year",
            ),
        ),
        migrations.AlterField(
            model_name="periodictrigger",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(
                blank=True,
                default=django_celery_beat.models.crontab_schedule_celery_timezone,
                help_text="Timezone to Run the Cron Schedule on. Default is UTC.",
                null=True,
                use_pytz=False,
                verbose_name="Cron Timezone",
            ),
        ),
    ]
