# Generated by Django 5.0.2 on 2024-03-29 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0018_improve_crontab_helptext"),
        ("trigger", "0003_alter_periodictrigger_day_of_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodictrigger",
            name="task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_celery_beat.periodictask",
            ),
        ),
    ]
