# Generated by Django 5.0.2 on 2024-06-24 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0025_alter_datanode_value"),
        ("trigger", "0004_periodictrigger_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodictrigger",
            name="flow_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periodic_triggers",
                to="flow.flowfile",
            ),
        ),
    ]
