# Generated by Django 5.0.2 on 2024-07-21 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow_new", "0007_conditionalnode_name"),
        ("trigger", "0005_periodictrigger_flow_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="periodictrigger",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="periodictrigger",
            name="day_of_month",
        ),
        migrations.RemoveField(
            model_name="periodictrigger",
            name="day_of_week",
        ),
        migrations.RemoveField(
            model_name="periodictrigger",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="periodictrigger",
            name="flow_file",
        ),
        migrations.RemoveField(
            model_name="periodictrigger",
            name="hour",
        ),
        migrations.RemoveField(
            model_name="periodictrigger",
            name="id",
        ),
        migrations.RemoveField(
            model_name="periodictrigger",
            name="minute",
        ),
        migrations.RemoveField(
            model_name="periodictrigger",
            name="month_of_year",
        ),
        migrations.RemoveField(
            model_name="periodictrigger",
            name="node",
        ),
        migrations.RemoveField(
            model_name="periodictrigger",
            name="scheduler_type",
        ),
        migrations.RemoveField(
            model_name="periodictrigger",
            name="timezone",
        ),
        migrations.RemoveField(
            model_name="periodictrigger",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="webhooktrigger",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="webhooktrigger",
            name="id",
        ),
        migrations.RemoveField(
            model_name="webhooktrigger",
            name="node",
        ),
        migrations.RemoveField(
            model_name="webhooktrigger",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="periodictrigger",
            name="basemodelwithtag_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="flow_new.basemodelwithtag",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="periodictrigger",
            name="target",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="flow_new.flow",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="webhooktrigger",
            name="basemodelwithtag_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="flow_new.basemodelwithtag",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="webhooktrigger",
            name="target",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="flow_new.flow",
            ),
            preserve_default=False,
        ),
    ]
