# Generated by Django 5.0.2 on 2024-07-13 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow_new", "0003_conditionalnodevalue"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="scope",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="local_flows",
                to="flow_new.flow",
            ),
        ),
        migrations.CreateModel(
            name="ScopeNode",
            fields=[
                (
                    "basenode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="flow_new.basenode",
                    ),
                ),
                (
                    "represent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="represent_scopes",
                        to="flow_new.flow",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
                "abstract": False,
            },
            bases=("flow_new.basenode",),
        ),
    ]
