# Generated by Django 5.0.2 on 2024-07-13 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow_new", "0003_conditionalnodevalue"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="scope",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="local_flows",
                to="flow_new.flow",
            ),
        ),
        migrations.AddField(
            model_name="foreachnode",
            name="block",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="block_node",
                to="flow_new.flow",
            ),
            preserve_default=False,
        ),
    ]
