# Generated by Django 5.0.2 on 2024-07-14 19:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow_new", "0004_flow_scope_foreachnode_block"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScopeBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "flow",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scope_block",
                        to="flow_new.flow",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="foreachnode",
            name="block",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="for_each_node",
                to="flow_new.scopeblock",
            ),
        ),
    ]
