# Generated by Django 5.0.2 on 2024-07-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow_new", "0006_conditionalnode_value_type_datanode_value_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conditionalnode",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
